### ISSUE TITLE
Pushing enter on backup directory prompt crashes PyWeather

### ISSUE THREAD

**Issue by creepersbane** [o355/PyWeather#23]
Where would you want me to backup the key to?
This is a directory. If I wanted my key at directory/backkey.txt,
You would enter 'directory'. The default directory is 'backup'.
Input here:

I pushed enter, expecting pyweather to automatically create and use the directory 'backup.'

Instead, I got this: 
Creating a backup...
Couldn't make the directory, does it exist?
Traceback (most recent call last):
  File "setup.py", line 846, in <module>
    open(folder_argument, 'w').close()
PermissionError: [Errno 13] Permission denied: '//backkey.txt'

I think the program should create the backup directory if no name is provided, something like:

def mkdir(directory):
    if not os.path.exists(directory):
        os.makedirs(directory)

**Comment by ModoUnreal** [comment]
I'll see if I can fix this today. Thanks for putting up the issue!

**Comment by o355** [comment]
I'll confirm the bug, and I'll do the fix. It should be as simple as adding an elif == "" to the code.

Thanks for reporting the issue!

**Comment by o355** [comment]
Bug is confirmed. Pushing out a hotfix now.

**Comment by o355** [comment]
I'll have to look into this issue a bit more. It's not as simple as adding an extra conditional.

**Comment by ModoUnreal** [comment]
Issue fixed, pull request will be made.

**Comment by ModoUnreal** [comment]
PR was made however it is in the pull request thats pending. Should I send you the code I added on Reddit?

**Comment by o355** [comment]
I'm actually fixing the issue right now. It's best if you abandon the PR.

**Comment by o355** [comment]
Issue has been fixed, pushing the commits now. Thanks for reporting the issue!

@ModoUnreal, I get a IFTTT trigger on my phone whenever a new issue gets created, so I hop on the issue pretty quickly. Thanks for your contributions, none the less!

**Comment by creepersbane** [comment]
Now it's doing this (had to force-kill python):
Traceback (most recent call last):
  File "configsetup.py", line 14, in <module>
    versioninfo = open('updater//versioninfo.txt').close()
FileNotFoundError: [Errno 2] No such file or directory: 'updater//versioninfo.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "configsetup.py", line 20, in <module>
    input()
KeyboardInterrupt

**Comment by creepersbane** [comment]
NVM scratch that.

**Comment by o355** [comment]
That's odd. I'll reopen the issue, and run some more investigations.

**Comment by o355** [comment]
Are you running on the indev branch? Have you pulled all the latest indev code from GitHub? Looking at the code, this should be working without a hitch.

**Comment by creepersbane** [comment]
I have all the latest code (as of yesterday at 9 PM)

I'll try updating to python 3.6 and see what happens.

**Comment by creepersbane** [comment]
Python 3.6 doesn't seem to be available for the RPI (which is what I do everything on)

**Comment by creepersbane** [comment]
an hour later... python is still building :/ Not my brightest idea.

**Comment by creepersbane** [comment]
Nice.
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting appJar
  Could not fetch URL https://pypi.python.org/simple/appjar/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement appJar (from versions: )
No matching distribution found for appJar

**Comment by o355** [comment]
Closing the issue for now, you should probably get to fixing your SSL libraries :)
