### ISSUE TITLE
Unable to install geopy automatically on windows in IDLE.

### ISSUE THREAD

**Issue by creepersbane** [o355/PyWeather#24]
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=============== RESTART: C:\Users\Benjamin\PyWeather\setup.py ===============
Your config likely isn't provisioned. Would you like to provision your config?
It's highly recommended you provision your config. If you decide not to,
you may run into issues using PyWeather.
Yes or No.
Input here: ywa
Couldn't understand your input. By default, I'm going to provision
your config. Beginning now...
Config file provisioned successfully! Moving on with PyWeather setup...
Welcome to PyWeather setup.
This is meant to run as a one-time program, when you first get PyWeather.

Running a few checks...

Before we get started, I want to confirm some permissions from you.
Is it okay if I use 1-5 MB of data (downloading libraries), save a small
text file called apikey.txt (> 2 KB), and automatically install Python
libraries?
Please input yes or no below:
Input here: yes

Cool! Let's start.
I'm going to start by checking for necessary libraries (to run PyWeather).
This can take a moment, so please hold tight while I check!
Deleting the PIP installer file (if it exists)
The file get-pip.py didn't exist, or we had wrong permissions.
All done!
Shucks. Not all necessary libraries are installed. Here's what needs to be installed:
- Colorama
- Geopy
- appJar
- Requests
If you want me to, I can automatically install these libraries.
Would you like me to do such? Yes or No.
Input here: yes
Now installing necessary libraries...
Installing Colorama...
Collecting colorama
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Installing collected packages: colorama
Successfully installed colorama-0.3.9
Installing geopy...
Collecting geocoder
  Downloading geocoder-1.29.1-py2.py3-none-any.whl (82kB)

[K    12% |###                             | 10kB 10.2MB/s eta 0:00:01
[K    24% |#######                         | 20kB 525kB/s eta 0:00:01
[K    37% |###########                     | 30kB 682kB/s eta 0:00:01
[K    49% |###############                 | 40kB 772kB/s eta 0:00:01
[K    62% |###################             | 51kB 825kB/s eta 0:00:01
[K    74% |#######################         | 61kB 841kB/s eta 0:00:01
[K    87% |###########################     | 71kB 843kB/s eta 0:00:01
[K    99% |############################### | 81kB 827kB/s eta 0:00:01
[K    100% |################################| 92kB 708kB/s 
Collecting requests (from geocoder)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)

[K    11% |###                             | 10kB ... 
[K    23% |#######                         | 20kB 4.1MB/s eta 0:00:01
[K    34% |###########                     | 30kB 2.8MB/s eta 0:00:01
[K    46% |##############                  | 40kB 2.0MB/s eta 0:00:01
[K    57% |##################              | 51kB 1.7MB/s eta 0:00:01
[K    69% |######################          | 61kB 1.5MB/s eta 0:00:01
[K    80% |#########################       | 71kB 1.3MB/s eta 0:00:01
[K    92% |#############################   | 81kB 1.2MB/s eta 0:00:01
[K    100% |################################| 92kB 940kB/s 
Collecting ratelim (from geocoder)
  Downloading ratelim-0.1.6-py2.py3-none-any.whl
Collecting click (from geocoder)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)

[K    14% |####                            | 10kB ... 
[K    28% |#########                       | 20kB 5.1MB/s eta 0:00:01
[K    43% |#############                   | 30kB 2.6MB/s eta 0:00:01
[K    57% |##################              | 40kB 2.0MB/s eta 0:00:01
[K    71% |#######################         | 51kB 1.7MB/s eta 0:00:01
[K    86% |###########################     | 61kB 1.5MB/s eta 0:00:01
[K    100% |################################| 71kB 1.0MB/s 
Collecting six (from geocoder)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->geocoder)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)

[K    7% |##                              | 10kB ... 
[K    15% |####                            | 20kB 5.1MB/s eta 0:00:01
[K    23% |#######                         | 30kB 2.8MB/s eta 0:00:01
[K    30% |#########                       | 40kB 2.0MB/s eta 0:00:01
[K    38% |############                    | 51kB 1.6MB/s eta 0:00:01
[K    46% |##############                  | 61kB 1.4MB/s eta 0:00:01
[K    54% |#################               | 71kB 1.2MB/s eta 0:00:01
[K    61% |###################             | 81kB 1.1MB/s eta 0:00:01
[K    69% |######################          | 92kB 1.1MB/s eta 0:00:01
[K    77% |########################        | 102kB 994kB/s eta 0:00:01
[K    85% |###########################     | 112kB 839kB/s eta 0:00:01
[K    92% |#############################   | 122kB 736kB/s eta 0:00:01
[K    100% |################################| 133kB 585kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->geocoder)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)

[K    7% |##                              | 10kB 5.1MB/s eta 0:00:01
[K    15% |####                            | 20kB 3.4MB/s eta 0:00:01
[K    23% |#######                         | 30kB 2.0MB/s eta 0:00:01
[K    30% |#########                       | 40kB 1.7MB/s eta 0:00:01
[K    38% |############                    | 51kB 1.4MB/s eta 0:00:01
[K    46% |##############                  | 61kB 1.3MB/s eta 0:00:01
[K    53% |#################               | 71kB 1.1MB/s eta 0:00:01
[K    61% |###################             | 81kB 1.0MB/s eta 0:00:01
[K    69% |######################          | 92kB 940kB/s eta 0:00:01
[K    76% |########################        | 102kB 906kB/s eta 0:00:01
[K    84% |###########################     | 112kB 781kB/s eta 0:00:01
[K    92% |#############################   | 122kB 691kB/s eta 0:00:01
[K    99% |############################### | 133kB 632kB/s eta 0:00:01
[K    100% |################################| 143kB 519kB/s 
Collecting idna<2.7,>=2.5 (from requests->geocoder)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)

[K    18% |#####                           | 10kB ... 
[K    36% |###########                     | 20kB 5.1MB/s eta 0:00:01
[K    54% |#################               | 30kB 2.6MB/s eta 0:00:01
[K    72% |#######################         | 40kB 2.0MB/s eta 0:00:01
[K    90% |#############################   | 51kB 1.6MB/s eta 0:00:01
[K    100% |################################| 61kB 1.0MB/s 
Collecting certifi>=2017.4.17 (from requests->geocoder)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)

[K    2% |                                | 10kB 10.2MB/s eta 0:00:01
[K    5% |#                               | 20kB 4.1MB/s eta 0:00:01
[K    8% |##                              | 30kB 2.2MB/s eta 0:00:01
[K    11% |###                             | 40kB 1.6MB/s eta 0:00:01
[K    14% |####                            | 51kB 1.3MB/s eta 0:00:01
[K    17% |#####                           | 61kB 1.2MB/s eta 0:00:01
[K    20% |######                          | 71kB 1.1MB/s eta 0:00:01
[K    23% |#######                         | 81kB 1.0MB/s eta 0:00:01
[K    26% |########                        | 92kB 930kB/s eta 0:00:01
[K    29% |#########                       | 102kB 882kB/s eta 0:00:01
[K    32% |##########                      | 112kB 752kB/s eta 0:00:01
[K    35% |###########                     | 122kB 664kB/s eta 0:00:01
[K    38% |############                    | 133kB 609kB/s eta 0:00:01
[K    41% |#############                   | 143kB 556kB/s eta 0:00:01
[K    43% |##############                  | 153kB 514kB/s eta 0:00:01
[K    46% |##############                  | 163kB 476kB/s eta 0:00:01
[K    49% |###############                 | 174kB 447kB/s eta 0:00:01
[K    52% |################                | 184kB 423kB/s eta 0:00:01
[K    55% |#################               | 194kB 399kB/s eta 0:00:01
[K    58% |##################              | 204kB 383kB/s eta 0:00:01
[K    61% |###################             | 215kB 364kB/s eta 0:00:01
[K    64% |####################            | 225kB 344kB/s eta 0:00:01
[K    67% |#####################           | 235kB 328kB/s eta 0:00:01
[K    70% |######################          | 245kB 313kB/s eta 0:00:01
[K    73% |#######################         | 256kB 293kB/s eta 0:00:01
[K    76% |########################        | 266kB 279kB/s eta 0:00:01
[K    79% |#########################       | 276kB 265kB/s eta 0:00:01
[K    82% |##########################      | 286kB 252kB/s eta 0:00:01
[K    84% |###########################     | 296kB 240kB/s eta 0:00:01
[K    87% |############################    | 307kB 230kB/s eta 0:00:01
[K    90% |#############################   | 317kB 220kB/s eta 0:00:01
[K    93% |#############################   | 327kB 212kB/s eta 0:00:01
[K    96% |##############################  | 337kB 204kB/s eta 0:00:01
[K    99% |############################### | 348kB 198kB/s eta 0:00:01
[K    100% |################################| 358kB 179kB/s 
Collecting decorator (from ratelim->geocoder)
  Downloading decorator-4.1.2-py2.py3-none-any.whl
Installing collected packages: urllib3, chardet, idna, certifi, requests, decorator, ratelim, click, six, geocoder
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 click-6.7 decorator-4.1.2 geocoder-1.29.1 idna-2.6 ratelim-0.1.6 requests-2.18.4 six-1.10.0 urllib3-1.22
Installing appJar...
Collecting appJar
  Downloading appJar-0.070.tar.gz (500kB)

[K    2% |                                | 10kB ... 
[K    4% |#                               | 20kB 1.5MB/s eta 0:00:01
[K    6% |#                               | 30kB 1.1MB/s eta 0:00:01
[K    8% |##                              | 40kB 853kB/s eta 0:00:01
[K    10% |###                             | 51kB 787kB/s eta 0:00:01
[K    12% |###                             | 61kB 830kB/s eta 0:00:01
[K    14% |####                            | 71kB 770kB/s eta 0:00:01
[K    16% |#####                           | 81kB 787kB/s eta 0:00:01
[K    18% |#####                           | 92kB 737kB/s eta 0:00:01
[K    20% |######                          | 102kB 741kB/s eta 0:00:01
[K    22% |#######                         | 112kB 635kB/s eta 0:00:01
[K    24% |#######                         | 122kB 628kB/s eta 0:00:01
[K    26% |########                        | 133kB 609kB/s eta 0:00:01
[K    28% |#########                       | 143kB 613kB/s eta 0:00:01
[K    30% |#########                       | 153kB 595kB/s eta 0:00:01
[K    32% |##########                      | 163kB 550kB/s eta 0:00:01
[K    34% |###########                     | 174kB 541kB/s eta 0:00:01
[K    36% |###########                     | 184kB 499kB/s eta 0:00:01
[K    38% |############                    | 194kB 494kB/s eta 0:00:01
[K    40% |#############                   | 204kB 459kB/s eta 0:00:01
[K    42% |#############                   | 215kB 461kB/s eta 0:00:01
[K    45% |##############                  | 225kB 433kB/s eta 0:00:01
[K    47% |###############                 | 235kB 419kB/s eta 0:00:01
[K    49% |###############                 | 245kB 390kB/s eta 0:00:01
[K    51% |################                | 256kB 370kB/s eta 0:00:01
[K    53% |#################               | 266kB 356kB/s eta 0:00:01
[K    55% |#################               | 276kB 335kB/s eta 0:00:01
[K    57% |##################              | 286kB 327kB/s eta 0:00:01
[K    59% |##################              | 296kB 309kB/s eta 0:00:01
[K    61% |###################             | 307kB 302kB/s eta 0:00:01
[K    63% |####################            | 317kB 283kB/s eta 0:00:01
[K    65% |####################            | 327kB 275kB/s eta 0:00:01
[K    67% |#####################           | 337kB 261kB/s eta 0:00:01
[K    69% |######################          | 348kB 252kB/s eta 0:00:01
[K    71% |######################          | 358kB 248kB/s eta 0:00:01
[K    73% |#######################         | 368kB 237kB/s eta 0:00:01
[K    75% |########################        | 378kB 232kB/s eta 0:00:01
[K    77% |########################        | 389kB 221kB/s eta 0:00:01
[K    79% |#########################       | 399kB 217kB/s eta 0:00:01
[K    81% |##########################      | 409kB 208kB/s eta 0:00:01
[K    83% |##########################      | 419kB 204kB/s eta 0:00:01
[K    85% |###########################     | 430kB 196kB/s eta 0:00:01
[K    87% |############################    | 440kB 194kB/s eta 0:00:01
[K    90% |############################    | 450kB 188kB/s eta 0:00:01
[K    92% |#############################   | 460kB 180kB/s eta 0:00:01
[K    94% |##############################  | 471kB 178kB/s eta 0:00:01
[K    96% |##############################  | 481kB 171kB/s eta 0:00:01
[K    98% |############################### | 491kB 170kB/s eta 0:00:01
[K    100% |################################| 501kB 149kB/s 
[31mException:
Traceback (most recent call last):
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
AttributeError: 'NoneType' object has no attribute 'encoding'[0m
Installing requests...
Requirement already satisfied: requests in c:\users\benjamin\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\benjamin\appdata\local\programs\python\python36\lib\site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\benjamin\appdata\local\programs\python\python36\lib\site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\benjamin\appdata\local\programs\python\python36\lib\site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\benjamin\appdata\local\programs\python\python36\lib\site-packages (from requests)
Sweet! All libraries should be installed.
Just to confirm, I'm double checking if needed libraries are installed.
Hmm...geopy didn't install properly.
As a last resort, we can use sudo -H to install packages.
Do you want to use the shell option to install geopy?
WARNING: Using the last-resort method may screw up PIP, and
may require you to reinstall PIP on your machine.Yes or No.
Input here: no
Not installing geopy with a shell command.
Cannot continue without geopy.
Press enter to exit.

>>> 

Sudo is not available on Windows, so that won't work.

**Comment by o355** [comment]
I'm pretty sure looking at the error log it's an issue with IDLE not being able to install PIP libraries from within itself.

PyWeather was designed to run in a shell, and not something like IDLE. I sadly can't fix this issue, it's more of an issue with IDLE and/or pip, and not my code.

If you want to run PyWeather in IDLE, I'd highly suggest installing the required libraries before running setup.

**Comment by creepersbane** [comment]
I would love to...
'pip3' is not recognized as an internal or external command,
operable program or batch file.
Guess I'm on my own.

**Comment by o355** [comment]
Try using `pip` instead. Sometimes `pip3` is `pip`.

**Comment by creepersbane** [comment]
I have both Python 2 and 3 installed. "Pip" is the Python 2 pip.

**Comment by o355** [comment]
I'd recommend reinstalling Python 3, and making sure that "Add Python to the PATH" is ticked off at the beginning of the installer, as far as I know. That should let you use pip from the command line.
