### ISSUE TITLE
Update check fail quits PyWeather without trying to get the weather.

### ISSUE THREAD

**Issue by creepersbane** [o355/PyWeather#26]
So, I was looking through the code to fix the "rounding on termux" bug, and I noticed that when the update check fails, it doesn't go ahead and try to get the weather. Instead, it exits. I feel like it should at least try to get the weather before quitting (HINT HINT my project keeps going even when it fails :)

If the weather check fails, it should show the cached data as long as it isn't out of date (the data, not PyWeather.)

Anyway, that's what I think. I would do it myself, but I don't feel like it (OK OK I will :P)

**Comment by o355** [comment]
I'll have to take a look at this. Unconfirmed for now, fixing another bug that was reported to me.

**Comment by o355** [comment]
I'll fix this bug (if it exists) once I finish up with QA for the upcoming release.

**Comment by creepersbane** [comment]
It's not really a bug, just a consequence of using sys.exit() after the error message.

**Comment by o355** [comment]
I'm going to call it a "bug", it was accidentally coded in a while ago and I didn't realize my mistake.

**Comment by creepersbane** [comment]
Ah ok

**Comment by creepersbane** [comment]
Close this now

**Comment by o355** [comment]
Bug has been fixed.
