### ISSUE TITLE
Missing variable "geoip_available"

### ISSUE THREAD

**Issue by creepersbane** [o355/PyWeather#28]
Exactly what the title says.

I fixed it :D 

How do I add my fixes to PyWeather?

**Comment by o355** [comment]
You'll need to fork PyWeather and submit a pull request. I'll have to take a look at this and see what's going on.

**Comment by creepersbane** [comment]
Hey, welcome to PyWeather!
Below, enter a location to check the weather for that location!
Traceback (most recent call last):
  File "/home/benjamin/Python/PyWeather/pyweather.py", line 485, in <module>
    if geoip_available is True:
NameError: name 'geoip_available' is not defined
