### ISSUE TITLE
Text-based logo

### ISSUE THREAD

**Issue by creepersbane** [o355/PyWeather#29]
This isn't really an issue more than an FYI

I made this beautiful work of art (still waiting for Wunderground to get back to me about using it):

[logo.txt](https://github.com/o355/PyWeather/files/1331420/logo.txt)

**Comment by o355** [comment]
Thanks for the logo. I think at the moment this won't be used, as it'll take up valuable space in the UI.

We're in a terminal, so I can't do much.

**Comment by o355** [comment]
Just as a quick reminder, I'll handle stuff like logo additions, and contacting Wunderground about anything. I'm the owner of this project. Thanks for your contributions, but I'll handle this stuff.

**Comment by creepersbane** [comment]
Ok

**Comment by creepersbane** [comment]
FYI, Wunderground says if a device has no GUI support, use their website link instead of a logo (yay no violating ToS' :smile:)

**Comment by o355** [comment]
Please note that I'm in charge of this project, so I'd handle things like contacting WU about their logo policy.

**Comment by creepersbane** [comment]
Yes, I know. I just wanted to let you know that you aren't breaking the TOS. 

On Oct 21, 2017, at 7:56 PM, o355 <notifications@github.com> wrote:

Please note that I'm in charge of this project, so I'd handle things like contacting WU about their logo policy.

**Comment by o355** [comment]
Alright, thanks for the info nonetheless.

I'm also going to abandon Halo as a spinner at this time. The monumental codebase changes will be too much for me to code in.

For your spinner library, I'd like to suggest a few things, but keep in mind I'm not into designing libraries just yet.
* Can you make the colors in the spinner (the actual spinner) use Colorama just so we're operating with the same library for the spinner & actual PyWeather colors?
* Halo has functionality where you can easily kill the spinner, and output `(red) x (white) Operation failed` or `(green) v (white) Operation succeeded!`, in a function like `spinner.fail(text="Operation failed)` or `spinner.succeed(text="Operation succeeded!")`. Could this get implemented?
* This isn't necessarily a suggestion but a requirement, but you'll need to get your spinner working for Python 3.

Thanks again for taking the time to code this in. I love the idea of having a progress spinner, but Halo didn't work, and I have no clue as how to go about making a library right now.

**Comment by creepersbane** [comment]
OK. 

I tested it in python 3, it worked just fine. In fact, it won't import in python 2. 

On Oct 21, 2017, at 10:48 PM, o355 <notifications@github.com> wrote:

Alright, thanks for the info nonetheless.

I'm also going to abandon Halo as a spinner at this time. The monumental codebase changes will be too much for me to code in.

For your spinner library, I'd like to suggest a few things, but keep in mind I'm not into designing libraries just yet.

Can you make the colors in the spinner (the actual spinner) use Colorama just so we're operating with the same library for the spinner & actual PyWeather colors?
Halo has functionality where you can easily kill the spinner, and output (red) x (white) Operation failed or (green) v (white) Operation succeeded!, in a function like spinner.fail(text="Operation failed) or spinner.succeed(text="Operation succeeded!"). Could this get implemented?
This isn't necessarily a suggestion but a requirement, but you'll need to get your spinner working for Python 3.
Thanks again for taking the time to code this in. I love the idea of having a progress spinner, but Halo didn't work, and I have no clue as how to go about making a library right now.

**Comment by o355** [comment]
Didn't realize we were on the text-based logo issue, whoops! Let's switch the conversation over to issue #33.
