### ISSUE TITLE
Fixing the progress bar 

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#33]
Presently the progress bar in PyWeather is a complete mess. I've been looking around for a library that can support the variability that comes with booting PyWeather (some people might have 15 or 25 steps to boot). 

I found a cool library called Halo on /r/coolgithubprojects, but it lacks Windows support at the moment.

**Comment by o355** [comment]
The library halo (https://github.com/ManrajGrover/halo) will be used. It doesn't have full Windows support, but works well enough for what has to be done.

**Comment by creepersbane** [comment]
Honestly, I could make a module using ANSI escape codes to do the progress bar. It would be Windows compatible (plus chopping off a dependency). Let me know what you think!

Benjamin Urquhart, President of Imfazwe.

**Comment by o355** [comment]
The halo library works well for my purposes on Windows. I did a test run on Win 10 and felt as if it worked and was easy to implement.

Of course I'm going to do further testing on OS X and Linux when I can.

**Comment by creepersbane** [comment]
Ok then :)

**Comment by o355** [comment]
Enhancement suspended temporarily, issues with the library were encountered.

**Comment by creepersbane** [comment]
Would you like me to make the custom module now? :P

**Comment by o355** [comment]
I've contacted the developers on GitHub, no response for 3 days.

I'm going to give them a week and then I'll give you permission to make the custom module, since I like having a fancy spinner.

**Comment by creepersbane** [comment]
Ok

**Comment by o355** [comment]
Development is now unsuspended. I'm going to investigate potential methods about using Halo, and potentially pushing back the feature to 0.6.4 beta since it may require monumental codebase changes.

@creepersbane, I appreciate your willingness to make a custom library! If you'd like to make one that'd be great, just to have a backup plan. If you can, try to get your package on PyPi, and I'll email you with more details.

**Comment by creepersbane** [comment]
I already have >:)

It's still a W.I.P, but you can see it at https://github.com/creepersbane/loading-spinner. 

If you want to try it, make sure you import spin_mod, NOT spinner. 

On Oct 20, 2017, at 8:21 PM, o355 <notifications@github.com> wrote:

Development is now unsuspended. I'm going to investigate potential methods about using Halo, and potentially pushing back the feature to 0.6.4 beta since it may require monumental codebase changes.

@creepersbane, I appreciate your willingness to make a custom library! If you'd like to make one that'd be great, just to have a backup plan. If you can, try to get your package on PyPi, and I'll email you with more details.

**Comment by o355** [comment]
Awesome! I'll try it out when I get the chance.

**Comment by o355** [comment]
Update: Two developers from their side have claimed that this is an odd issue, I'm going to investigate into more detail why this is occurring.

**Comment by creepersbane** [comment]
Ok then.

Status on the custom library:
NOTE: I have not uploaded the code to Github yet. Maybe tonight :)

Spinner text colors: 100% (use setTextColor(color) to set the color)
Spinner frames color: 90% (use setSpinnerColor(color) to set the color)
Spinner fail function: 0% (working on that now)
Spinner succeed function: 0% (also working on that now)

**Comment by o355** [comment]
Alright. I'm considering using your library instead, but just make sure you get it up on PyPi so that users can download it with pip install.

**Comment by creepersbane** [comment]
Ok

**Comment by o355** [comment]
Hey @creepersbane, I've decided to bite the bullet and stick with Halo for now.

Halo is an official library which has been starred thousands of times, and even though I have to add 500ish `Style.BRIGHT` statements, I should of done that when I first did color in PyWeather.

Thank you for your willingness to make a library for PyWeather, nonetheless.

Development of the spinner has resumed.

**Comment by creepersbane** [comment]
Ok. I'm still adding it to Pypi though :)

On Oct 25, 2017, at 10:45 AM, o355 <notifications@github.com> wrote:

Hey @creepersbane, I've decided to bite the bullet and stick with Halo for now.

Halo is an official library which has been starred thousands of times, and even though I have to add 500ish Style.BRIGHT statements, I should of done that when I first did color in PyWeather.

Thank you for your willingness to make a library for PyWeather, nonetheless.

Development of the spinner has resumed.

**Comment by creepersbane** [comment]
FYI, the text dimming with halo happens to me as well (Ubuntu 14.0.4 xenial)

**Comment by o355** [comment]
I sent an email that should show up here...well thanks GitHub

**Comment by creepersbane** [comment]
It showed up. 

On Oct 25, 2017, at 2:12 PM, o355 <notifications@github.com> wrote:

I sent an email that should show up here...well thanks GitHub

**Comment by o355** [comment]
Cool. If you wouldn't mind, it'd be nice if you could subscribe to the weekly mailing letter for PyWeather's latest news. I don't want Mailerlite kicking me for using their service unnecessarily.

**Comment by creepersbane** [comment]
Eh, OK?

**Comment by creepersbane** [comment]
I'm not getting any emails. 

On Oct 25, 2017, at 8:02 PM, o355 <notifications@github.com> wrote:

Cool. If you wouldn't mind, it'd be nice if you could subscribe to the weekly mailing letter for PyWeather's latest news. I don't want Mailerlite kicking me for using their service unnecessarily.

**Comment by o355** [comment]
Done, I actually can't believe the code for 0.6.3 beta is done butttt it's QA time

**Comment by creepersbane** [comment]
Just as a little gag, set the spinner text at the very end after fetching the weather to "Voting for net neutrality..." :)

On Nov 9, 2017, at 8:16 AM, o355 <notifications@github.com> wrote:

Closed #33.

**Comment by o355** [comment]
It's a good idea but the text would either flash on screen for 50ms or I'd have to intentionally put a sleep for maybe 300ms to show the spinner.

**Comment by creepersbane** [comment]
Make it flash so people will double take :)

On Nov 25, 2017, at 7:01 PM, o355 <notifications@github.com> wrote:

It's a good idea but the text would either flash on screen for 50ms or I'd have to intentionally put a sleep for maybe 300ms to show the spinner.
