### ISSUE TITLE
setup.py should say "press enter 14 times to enter API key"

### ISSUE THREAD

**Issue by theletterandrew** [o355/PyWeather#37]
Just noticed this when trying to run setup.py in hopes of fixing another issue.

**Comment by creepersbane** [comment]
Lol

**Comment by theletterandrew** [comment]
If you hit enter 15 times, it asks you to confirm your (empty) api key lol

**Comment by theletterandrew** [comment]
I'm fixing this btw

**Comment by theletterandrew** [comment]
Created a new pull request (I hope I did that right- I'm brand new to coding with a group using github), so I'll close this issue when the pull request has been accepted.

**Comment by o355** [comment]
Thanks for the PR, guess I didn't count right. I'll close this issue and accept your PR now.
