### ISSUE TITLE
Bug(s): Issues with writing new version info files & out of directory errors

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#44]
The versioninfo file fails to load, and is improperly caught. This error can also occur when your version info file is missing.

Checklist:
- [ ] Fix the bug
- [ ] Test the bug fix

**Comment by creepersbane** [comment]
Have you considered making the version a variable in pyweather.py?

**Comment by o355** [comment]
What happens right now is that we load a separate versioninfo file that can be used across different scripts for determining a user's PyWeather version, especially when running configupdate

**Comment by o355** [comment]
Work has started on this bug fix.

**Comment by o355** [comment]
The issue is fixed. Old code caused problems. We're now assuming the user has a version info file.
