### ISSUE TITLE
Feature: Mars Weather

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#49]
Description: Adding the weather on Mars via. a separate API. Current conditions will be available, historical data will NOT be available.

This can be added as a favorite location since the code will be outright separated. 

Low priority: This is a low priority feature, and this feature will be dropped if this takes too long to implement  (or at least keeping current conditions).

Checklist:
- [ ] Playing around with the API
- [ ] Adding location input & menu option support (restrict if it's a mars location)
- [ ] Adding API support
- [ ] Adding parsing support
- [ ] Adding config options

Estimated completion date: January 23, 2017

**Comment by ModoUnreal** [comment]
So is this API still Wunderground, if not what is it. I'd quite like to play around with it, also I'm pretty much done with the installer, however I'll tell you this tomorrow (you heard nothing!)

**Comment by o355** [comment]
The API is http://marsweather.ingenology.com. It seems very easy to work with but implementing it into PyWeather might be hard. Who knows.

**Comment by ModoUnreal** [comment]
I've kinda played around with it. I'm going to start to implement it today. Also why no historical data? It is possible!

**Comment by o355** [comment]
It would require a lot of unnecessary work to adapt historical data for proper functioning.

**Comment by ModoUnreal** [comment]
Oh alright, I'll avoid historical data and stick to latest data.

**Comment by ModoUnreal** [comment]
For some reason the marsweather website seems to be down, I'll see how long it takes for it come back up.
It was working before!

**Comment by o355** [comment]
Ouch...at this point given the stability of the MAAS API I'm going to scrap this feature. Quality > Quantity when it comes to features. Given you commented 21 hours ago when I comment now and that the API isn't up yet I'm not willing to add in this feature.

Sorry about this @ModoUnreal, hope you can understand why I'll be dropping this feature.

**Comment by ModoUnreal** [comment]
Yeah sure, I completely understand!
