### ISSUE TITLE
Parse error for current conditions

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#55]
Location input: "South Pole"

PyWeather crashes and now the penguins in the south pole are sad since they can't see the weather

**Comment by creepersbane** [comment]
Why did you even try that location :P

**Comment by o355** [comment]
Working on the issue. For whatever reason a json parse error occurs, but I have seen fails on the current conditions variable.

Now working to make sure these are tried and properly caught

**Comment by o355** [comment]
I can't replicate the issue, but if anyone wants the weather for the south pole just enter "McMurdo Station"

**Comment by o355** [comment]
Issue fixed.
