### ISSUE TITLE
Use secure API endpoints by default

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#67]
At this point we need to try and use secure APIs. PyWeather by default isn't using HTTPS.

EDIT: We will not test machines if they're HTTPS compatible or not, but instead catch if a SSL exception occurs.

Things to do:
- [x] Modify all URLs to enable SSL support
- [x] Modify all requests.get to make SSL work
- [ ] Modify all other scripts to make SSL work

**Comment by creepersbane** [comment]
You can use a try/except block to catch an SSL exception (or whatever exception is thrown when SSL is disabled/nonexistent).

**Comment by o355** [comment]
That's what I was thinking. I just realized that every single request in pyweather has exception handling. First comes the HTTPS requests, if it fails try an HTTP request, if that fails then there's a problem.Should be pretty easy to implement and really for anyone else to implement.WUs API just needs https:// instead of http://.GeoNames needs https://secure.geonames.orgI don't know about freegeoip however.On Feb 25, 2018 9:49 AM, creepersbane <notifications@github.com> wrote:You can use a try/except block to catch an SSL exception (or whatever exception is thrown when SSL is disabled/nonexistent).

**Comment by o355** [comment]
Working on this feature now. We'll just check for an SSL exception.

**Comment by o355** [comment]
So far, so good. I've been working on adding _https variables whenever a URL is declared in PyWeather. Things are coming along nicely.

**Comment by o355** [comment]
All variables with a URL in it now have a `_https` counterpart. Now it's time to experiment with truly enabling HTTPS support.

**Comment by o355** [comment]
I'm continuing to work on upgrading all requests blocks of code to have HTTPS support. So far the main loading is about 1/2 done.

**Comment by o355** [comment]
Still working on this, now the main loading is 100% HTTPS ready. Doing some testing and the rest of the script should be HTTPS compatible.

ETA for finishing is some time in the next 2 weeks.

**Comment by o355** [comment]
It works! Wireshark is reporting all API requests are now using HTTPS, instead of sending it in the clear.

**Comment by o355** [comment]
Going to finish adding HTTPS support today.

I'll also be sure to add a warning message in the debugger for each try block.

**Comment by o355** [comment]
The main script has 100% support for HTTPS, now working on other scripts.

**Comment by o355** [comment]
All done, PyWeather now has HTTPS support.
