### ISSUE TITLE
Finding a new Geo IP API

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#77]
Freegeoip.net is being depreciated on July 1st.

Time to find a new API!

**Comment by o355** [comment]
So here's the deal. There really is no good API that's free and has HTTPS support. Can't get everything free in life.

To make sure there is a geo ip system in PyWeather that supports API we will use ipstack for HTTPS requests and ip-api.com for HTTP requests. The user  will be able to decide which API they want to use.

More info will come soon.

**Comment by o355** [comment]
Upon further investigation, ipstack isn't fesible, and the free plan doesn't include SSL support.

ip-api.com it is

**Comment by o355** [comment]
It's ip-api.org. ip-api.com is blocked by my Pi-Hole, and so is ip-api.org.

I'll continue to look into this feature.

**Comment by o355** [comment]
ip-api.com is being blocked by my Pi-Hole, and is found on many ad server lists. As such, we need to find a new Geo IP API.

If we can't find a new API by v1.0.0 the Geo IP feature may have to be dropped.

**Comment by BenjaminUrquhart** [comment]
I have a content blocker on my computer, but this one seems to work: https://ipapi.co/

It has https, and there shouldn't be any issues with rate limits (unless someone checks their local weather 1000 times a day)

**Comment by o355** [comment]
Alright that's good to hear.

**Comment by o355** [comment]
Looks like we found a new Geo API, so I'm closing this issue for now.
