### ISSUE TITLE
Issue with Termux not reading API keys properly

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#78]
I've been running into a recent issue where Termux cannot properly read the API key.

It looks like Termux is adding empty space to the API key. I'm going to have to experiment with fixing this issue.

**Comment by o355** [comment]
Reopening this issue as there's issues now in the setup file with invalid API key reading.

Probably going to add tab support in the replace in pyweather.py and the same code in setup.py as well.

**Comment by BenjaminUrquhart** [comment]
Looks like the same thing needs to be done to the setup script

**Comment by o355** [comment]
Yeah, probably needs to go in the input for an API key.

Just note that there are 2 inputs for an API key, and that it really only happens when you copy & paste a key. Typing it out is fine.
