### ISSUE TITLE
Adding an asciinema demo to the readme

### ISSUE THREAD

**Issue by o355** [o355/PyWeather#8]
I'll need to add an asciinema demonstration to the readme at some point. Tried doing it before, but I made a few mistakes.

**Comment by o355** [comment]
Hey, 4 months later, no asciinema demo on the readme! Nice!

**Comment by o355** [comment]
Hey, 5.5 months later, no asciinema demo on the readme! Nice!

**Comment by creepersbane** [comment]
Nice!

**Comment by o355** [comment]
Hey, 6.5 months later, no asciinema demo on the readme! Nice!

**Comment by creepersbane** [comment]
Hey, 7 months later, no asciilema demo on the readme! Nice!

**Comment by o355** [comment]
Hey, 6.900001 months later, no asciinema demo on the readme! Nice!

**Comment by creepersbane** [comment]
OMG I was so close :P

**Comment by o355** [comment]
Hey, 7 months and 2 days later, no asciinema demo on the readme! Nice!

**Comment by o355** [comment]
Hey, I'm actually making a VM to do an asciinemo demo right now! Woo hoo!

**Comment by o355** [comment]
The asciinema demo was recorded! I'll be adding it to the readme in the morning.

**Comment by creepersbane** [comment]
Hey, 3 days later, no asciilema demo on the readme! Nice!

**Comment by o355** [comment]
Hey, I've been really lazy lately! F1 2016 > Python development

**Comment by creepersbane** [comment]
Schoolwork > everything.

**Comment by o355** [comment]
I'm going to add that asciinema demo right now.

**Comment by o355** [comment]
Today, we have to say goodbye to this issue. It lived a long and fulfilling 8 months and 9 days, and managed to stick around for at least 2 (probably 3) releases.

Rest in peace issue 8
4/11/2017 - 12/20/2017
